server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PATCH
              - PUT
              - DELETE
              - OPTIONS
              - HEAD
            allowedHeaders: "*"
      routes:
        - id: products
          uri: http://localhost:8081
          predicates:
            - Path=/shop-demo/products**, /shop-demo/level-2/products**
        - id: orders
          uri: http://localhost:8081
          predicates:
            - Path=/shop-demo/orders**, /shop-demo/level-2/orders**
        - id: productEventInformations
          uri: http://localhost:8081
          predicates:
            - Path=/shop-demo/productEventInformations**

# Eureka
eureka:
  client:
    enabled: true
