spring:
  profiles:
    active:
      - local
  jackson:
    serialization:
      INDENT_OUTPUT: true
  cloud:
    gateway:
      forwarded:
        enabled: false
      x-forwarded:
        proto-enabled: true
        proto-append: true
        enabled: true
        port-enabled: false
      routes:
        - id: shop-demo
          uri: lb://shop-demo-ms
          predicates:
            - Path=/shop-demo/**
        - id: team-1
          uri: lb://fae-team-1-service-ms
          predicates:
            - Path=/team-1/**
        - id: team-2
          uri: lb://fae-team-2-service
          predicates:
            - Path=/team-2/**
        - id: team-3
          uri: lb://fae-team-3-service
          predicates:
            - Path=//team-3/**
        - id: team-4
          uri: lb://team4-service-ms
          predicates:
            - Path=/team-4/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans,shutdown"
      cors:
        allowed-methods:
          - GET
