server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "https://coalbase.archi-lab.io, https://coalbase.archi-lab.de"
            allowedMethods:
              - GET
              - POST
              - PATCH
              - PUT
              - DELETE
              - OPTIONS
              - HEAD
            allowedHeaders: "*"
      routes:
        - id: products
          uri: lb://shop-demo-ms
          predicates:
            - Path=/shop-demo/products**, /shop-demo/level-2/products**
        - id: orders
          uri: lb://shop-demo-ms
          predicates:
            - Path=/shop-demo/orders**, /shop-demo/level-2/orders**
        - id: productEventInformations
          uri: lb://shop-demo-ms
          predicates:
            - Path=/shop-demo/productEventInformations**

# Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-1:8761/eureka/,http://eureka-2:8761/eureka/
